Repository vrn-sh/erp, pull requests merged in 2023-12, with the labels that each got.

#377 fix(web): profile page undefined error
  web/src/pages/Profile/Profile.tsx
Labels: front-end

#379 feat(web): Add page rempli d'info duser
  web/src/App.tsx
  web/src/pages/Login/Login.tsx
  web/src/pages/Settings/Settings-pages/setting-account.tsx
  web/src/pages/Settings/Settings.scss
  web/src/pages/SignUp/InfoForm.tsx
  web/src/pages/SignUp/SignUp.scss
Labels: enhancement, front-end, in-pld

#385 fix(api): shellcode encoding form
  web/.env-dist
  web/package.json
  web/src/assets/strings/en/basicpayload.json
  web/src/assets/strings/en/myph.json
  web/src/assets/strings/en/payload.json
  web/src/pages/Dashboard/Accueil.tsx
  web/src/pages/Dashboard/shellcode/BasicShellcode.tsx
  web/src/pages/Dashboard/shellcode/LinkDisplay.tsx
  web/src/pages/Dashboard/shellcode/MyPhShellcode.tsx
  web/src/pages/Dashboard/shellcode/PayLoadForm.tsx
Labels: enhancement, front-end, in-pld

#373 feat(api): mailing-list registration
  api/api/migrations/0024_mailinglistitem.py
  api/api/migrations/0028_merge_0024_mailinglistitem_0027_merge_20231116_1548.py
  api/api/models/mailing_list.py
  api/api/serializers/mailing_list.py
  api/api/tests/mailing_list_test.py
  api/api/views/viewsets/mailing_list.py
  api/core/urls.py
  web/src/component/Footer/Footer.scss
  web/src/component/Footer/Footer.tsx
  web/src/pages/Login/Login.scss
Labels: enhancement, front-end, back-end

#386 feat(api): Finalize MFA
  api/.env-dist
  api/api/migrations/0028_auth_has_otp.py
  api/api/migrations/0029_auth_mfa_secret.py
  api/api/models/__init__.py
  api/api/views/mfa.py
  api/core/urls.py
  api/requirements.txt
Labels: back-end
