Repository vrn-sh/erp, pull requests merged in 2023-07, with the labels that each got.

#237 fix(build): setting fixed version for every docker image
  api/Dockerfile
  api/requirements.txt
  docker-compose-dev.yml
  docker-compose.yml
  web/Dockerfile
  web/nginx.conf
  web/package.json
Labels: bug, ci / deployment

#226 feat(api): added hunter.io integration
  api/.env-dist
  api/api/services/hunter.py
  api/api/tests/hunter_tests.py
  api/api/views/hunter.py
  api/core/urls.py
Labels: back-end

#240 feat(api): added clientInfo model to retrieve all the informations ab…
  api/api/migrations/0009_alter_vulnerability_options_clientinfo.py
  api/api/models/client_infos.py
  api/api/serializers/client_infos.py
  api/api/tests/clientinfo_tests.py
  api/api/views/viewsets/client_info.py
  api/core/urls.py
Labels: back-end

#243 feat(api): add favoris to the Auth Model
  api/api/migrations/0009_alter_vulnerability_options_auth_favorites_and_more.py
  api/api/migrations/0010_merge_20230713_1322.py
  api/api/models/__init__.py
  api/api/serializers/__init__.py
Labels: back-end

#241 feat(web): vulnerability detail page
  web/package.json
  web/src/App.tsx
  web/src/pages/Dashboard/SubDashboards/Vulnerability.tsx
  web/src/pages/Vulnerability/AddVul.tsx
  web/src/pages/Vulnerability/EditVuln.tsx
  web/src/pages/Vulnerability/VulnDetail.tsx
  web/src/pages/Vulnerability/Vulnerability.scss
Labels: enhancement, front-end, in-pld

#248 fix(api): change favorites type and update clientInfo routes
  api/api/migrations/0009_alter_vulnerability_options_auth_favorites_and_more.py
  api/api/migrations/0010_merge_20230713_1322.py
  api/api/migrations/0011_remove_auth_favorites_auth_favorites.py
  api/api/models/__init__.py
  api/api/views/viewsets/client_info.py
Labels: back-end

#250 Feat/add manager profile image
  api/api/migrations/0012_auth_profile_image.py
  api/api/models/__init__.py
  api/api/models/vulns.py
  api/api/serializers/__init__.py
  api/api/serializers/utils.py
  api/api/serializers/vulns.py
Labels: back-end
