Repository vrn-sh/erp, pull requests merged in 2023-04, with the labels that each got.

#105 Release 0.0.8 :sparkles:
  web/README.md
  web/src/assets/strings/en/dorks.json
  web/src/assets/strings/en/vulnerabilities.json
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/SubDashboard.tsx
  web/src/pages/Dashboard/SubDashboards/DorkEngine.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
Labels: release

#107 fix(ci): deployment workflow should only run if all others are successful
  .github/workflows/api-unit-tests.yml
  .github/workflows/compose.yml
  .github/workflows/deploy.yml
  .github/workflows/frontend-lint.yml
Labels: ci / deployment

#106 feat(web): cosmetics
  .github/workflows/frontend-lint.yml
  api/scripts/setup_mac.sh
  web/package.json
  web/src/App.tsx
  web/src/component/NavBar/NavBar.tsx
  web/src/pages/Error/Error.tsx
  web/src/pages/Home/Form/ContactForm.module.scss
  web/src/pages/Home/Form/ContactForm.tsx
  web/src/pages/Home/Home.tsx
  web/yarn.lock
Labels: front-end

#109 feat(api): adding `Nmap` CRUD
  api/api/migrations/0002_nmapscan.py
  api/api/models/mission.py
  api/api/models/utils.py
  api/api/permissions.py
  api/api/serializers/mission.py
  api/api/tests/helpers.py
  api/api/tests/notes_tests.py
  api/api/views/viewsets/mission.py
  api/core/urls.py
  api/requirements.txt
Labels: back-end

#110 feat(api): fixing documentation endpoint
  api/api/models/utils.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/mission.py
  api/api/views/viewsets/vulns.py
Labels: documentation

#108 feat(web): note cards
  web/src/component/SideBar/SideBar.scss
  web/src/pages/Dashboard/DashBoardNote.type.tsx
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/SubDashboards/Notes.tsx
Labels: enhancement, front-end, in-pld

#111 fix(api): Upgrading auth-token management system
  api/Dockerfile
  api/api/serializers/__init__.py
  api/api/tests/__init__.py
  api/api/tests/helpers.py
  api/api/views/__init__.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/mission.py
  api/api/views/viewsets/vulns.py
  api/core/settings.py
  api/core/urls.py
  api/requirements.txt
  api/scripts/setup.sh
Labels: enhancement, back-end

#112 :sparkles: Release 0.0.10
  .github/workflows/api-unit-tests.yml
  .github/workflows/compose.yml
  .github/workflows/deploy.yml
  .github/workflows/frontend-lint.yml
  api/Dockerfile
  api/api/migrations/0002_nmapscan.py
  api/api/models/mission.py
  api/api/models/utils.py
  api/api/permissions.py
  api/api/serializers/__init__.py
  api/api/serializers/mission.py
  api/api/tests/__init__.py
  api/api/tests/helpers.py
  api/api/tests/notes_tests.py
  api/api/views/__init__.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/mission.py
  api/api/views/viewsets/vulns.py
  api/core/settings.py
  api/core/urls.py
  api/requirements.txt
  api/scripts/setup.sh
  api/scripts/setup_mac.sh
  web/package.json
  web/src/App.tsx
  web/src/component/NavBar/NavBar.tsx
  web/src/component/SideBar/SideBar.scss
  web/src/pages/Dashboard/DashBoardNote.type.tsx
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/SubDashboards/Notes.tsx
  web/src/pages/Error/Error.tsx
  web/src/pages/Home/Form/ContactForm.module.scss
  web/src/pages/Home/Form/ContactForm.tsx
  web/src/pages/Home/Home.tsx
  web/yarn.lock
Labels: release

#114 feat(api): adding support for `MinIO`
  .gitignore
  api/.env-dist
  api/api/services/minio.py
  api/core/settings.py
  api/requirements.txt
  docker-compose.yml
  services/nginx/nginx.conf
Labels: enhancement

#115 feat(web): setting page
  web/.eslintrc.cjs
  web/Makefile
  web/package.json
  web/src/App.tsx
  web/src/component/SideBar/SideBar.tsx
  web/src/pages/Settings/Settings-pages/billing.scss
  web/src/pages/Settings/Settings-pages/set-billing.tsx
  web/src/pages/Settings/Settings-pages/set-notif.tsx
  web/src/pages/Settings/Settings-pages/set-security.tsx
  web/src/pages/Settings/Settings-pages/set-team.tsx
  web/src/pages/Settings/Settings-pages/setting-account.tsx
  web/src/pages/Settings/Settings-pages/team.scss
  web/src/pages/Settings/Settings.scss
  web/src/pages/Settings/Settings.tsx
  web/yarn.lock
Labels: front-end

#117 feat(web): Create/Edit mission UI
  web/.eslintrc.cjs
  web/package.json
  web/src/App.tsx
  web/src/assets/cover.jpg
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/EditMission/CreateMission.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/EditMission/Mission.scss
  web/src/pages/Profile/Profile.scss
  web/src/pages/Profile/Profile.tsx
  web/yarn.lock
Labels: enhancement, front-end

#118 fix(web): Login request
  .github/workflows/deploy.yml
  web/Makefile
  web/package.json
  web/src/App.tsx
  web/src/config.ts
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/Login/Login.tsx
  web/yarn.lock
Labels: bug, front-end

#119 Release 0.0.11 :sparkles:
  .github/workflows/deploy.yml
  .gitignore
  api/.env-dist
  api/api/services/minio.py
  api/core/settings.py
  api/requirements.txt
  docker-compose.yml
  services/nginx/nginx.conf
  web/.eslintrc.cjs
  web/Makefile
  web/package.json
  web/src/App.tsx
  web/src/assets/cover.jpg
  web/src/component/SideBar/SideBar.tsx
  web/src/config.ts
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/EditMission/CreateMission.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/EditMission/Mission.scss
  web/src/pages/Login/Login.tsx
  web/src/pages/Profile/Profile.scss
  web/src/pages/Profile/Profile.tsx
  web/src/pages/Settings/Settings-pages/billing.scss
  web/src/pages/Settings/Settings-pages/set-billing.tsx
  web/src/pages/Settings/Settings-pages/set-notif.tsx
  web/src/pages/Settings/Settings-pages/set-security.tsx
  web/src/pages/Settings/Settings-pages/set-team.tsx
  web/src/pages/Settings/Settings-pages/setting-account.tsx
  web/src/pages/Settings/Settings-pages/team.scss
  web/src/pages/Settings/Settings.scss
  web/src/pages/Settings/Settings.tsx
  web/yarn.lock
Labels: release

#120 fix(web): add-team popup style fix
  web/src/component/SideBar/SideBar.tsx
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Settings/Settings-pages/set-team.tsx
  web/src/pages/Settings/Settings-pages/team.scss
Labels: bug, front-end

#121 feat(web): vulnerability UI page
  web/.eslintrc.cjs
  web/Makefile
  web/package.json
  web/src/App.tsx
  web/src/pages/Settings/Settings.tsx
  web/src/pages/Vulnerability/Add.tsx
  web/src/pages/Vulnerability/Vulnerability.scss
  web/yarn.lock
Labels: front-end

#116 feat(api): adding Screenshots to Vulnerability model
  api/.env-dist
  api/api/migrations/0001_initial.py
  api/api/migrations/0002_alter_vulnerability_images.py
  api/api/migrations/0002_nmapscan.py
  api/api/models/__init__.py
  api/api/models/mission.py
  api/api/models/vulns.py
  api/api/permissions.py
  api/api/serializers/__init__.py
  api/api/serializers/mission.py
  api/api/serializers/vulns.py
  api/api/services/minio.py
  api/api/services/s3.py
  api/api/tests/__init__.py
  api/api/tests/helpers.py
  api/api/tests/mission_tests.py
  api/api/tests/notes_tests.py
  api/api/tests/vuln_tests.py
  api/api/views/__init__.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/mission.py
  api/api/views/viewsets/vulns.py
  api/core/settings.py
  api/requirements.txt
  api/scripts/setup.sh
  docker-compose.yml
  services/mc/entrypoint.sh
Labels: back-end

#126 (web)Fix signup/role
  api/api/views/viewsets/__init__.py
  web/src/component/NavBar/NavBar.tsx
  web/src/config.ts
  web/src/pages/SignUp/SignUp.scss
  web/src/pages/SignUp/SignUp.tsx
  web/src/pages/Vulnerability/Add.tsx
Labels: front-end

#127 feat(api): sending ResetPassword & ConfirmAccount emails
  api/api/migrations/0003_rename_is_disabled_auth_is_enabled_and_more.py
  api/api/models/__init__.py
  api/api/serializers/__init__.py
  api/api/tests/helpers.py
  api/api/views/__init__.py
  api/core/settings.py
  api/core/urls.py
  docker-compose.yml
Labels: back-end

#130 fix(web): add mission button
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
Labels: bug, front-end

#129 feat(web): API-calls for notes
  web/package.json
  web/src/component/Button.tsx
  web/src/component/SideBar/SideBar.scss
  web/src/config.ts
  web/src/pages/Dashboard/DashBoardNote.type.tsx
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/SubDashboards/Notes.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/AddNote.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/Notes.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/ViewNote.tsx
  web/src/pages/Login/Login.tsx
Labels: enhancement, front-end, in-pld

#132 Api integration missions + Permission
  web/package.json
  web/src/component/Feedback.tsx
  web/src/component/SideBar/SideBarData.tsx
  web/src/component/SideBar/TopBar.tsx
  web/src/main.scss
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/DashboardMission.type.ts
  web/src/pages/Dashboard/SubDashboards/DorkEngine.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/AddNote.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/Notes.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/ViewNote.tsx
  web/src/pages/EditMission/CreateMission.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/Login/Login.tsx
Labels: enhancement, front-end, in-pld

#133 feat(api): adding support for `crt.sh` API
  api/api/migrations/0006_crtsh.py
  api/api/models/mission.py
  api/api/serializers/mission.py
  api/api/services/crtsh.py
  api/api/views/viewsets/mission.py
  api/core/urls.py
Labels: back-end

#136 feat(web): UI mission detail
  web/.env.example
  web/package.json
  web/src/App.tsx
  web/src/assets/strings/en/mission_scope.json
  web/src/component/SideBar/SideBar.scss
  web/src/component/SideBar/SideBarData.tsx
  web/src/component/SideBar/TopBar.tsx
  web/src/config.ts
  web/src/global-variable.scss
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/MissionDetail/MissionDetail.scss
  web/src/pages/MissionDetail/MissionDetail.tsx
  web/src/pages/MissionDetail/Scope.tsx
  web/src/pages/SignUp/SignUp.scss
  web/src/pages/Vulnerability/AddVul.tsx
  web/yarn.lock
Labels: front-end, dependencies

#138 feat(web): Team UI & API calls
  web/src/App.tsx
  web/src/component/DeleteConfirm.tsx
  web/src/component/SideBar/SideBarData.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/EditMission/CreateMission.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/Team/CreateTeam.tsx
  web/src/pages/Team/EditTeam.tsx
  web/src/pages/Team/Team.tsx
  web/src/pages/Team/TeamList.tsx
Labels: enhancement, front-end
