Repository vrn-sh/erp, pull requests merged in 2023-05, with the labels that each got.

#140 feat(web): Intégration service de mail au form de contact au front
  web/.env.example
  web/package.json
  web/src/pages/Home/Form/ContactForm.tsx
Labels: front-end, dependencies

#141 fix(api): `send_confirm_email()` would not trigger in some cases
  api/api/migrations/0007_alter_auth_is_enabled.py
  api/api/models/__init__.py
  api/core/urls.py
  web/yarn.lock
Labels: bug, back-end

#143 fix(api): values would not be correctly set in cache
  api/api/models/__init__.py
  api/api/views/__init__.py
Labels: bug, back-end

#145 feat(web): Ajout la page et le popup de confirmation de mail
  web/package.json
  web/src/App.tsx
  web/src/pages/SignUp/ConfirmEmail.tsx
  web/src/pages/SignUp/SignUp.scss
  web/src/pages/SignUp/SignUp.tsx
Labels: front-end, dependencies, in-pld

#137 feat(api): added sendgrid pip package to send the confirmation and re…
  .github/workflows/api-unit-tests.yml
  api/api/models/__init__.py
  api/api/services/__init__.py
  api/api/services/sendgrid_mail.py
  api/requirements.txt
Labels: back-end

#150 feat(api): adding scope field to Mission model
  api/api/management/middlewares.py
  api/api/migrations/0001_initial.py
  api/api/migrations/0002_alter_vulnerability_images.py
  api/api/migrations/0003_rename_is_disabled_auth_is_enabled_and_more.py
  api/api/migrations/0004_notes_title.py
  api/api/migrations/0005_alter_mission_team_alter_team_leader.py
  api/api/migrations/0006_crtsh.py
  api/api/migrations/0007_alter_auth_is_enabled.py
  api/api/models/mission.py
  api/api/serializers/mission.py
  api/api/tests/helpers.py
  api/api/tests/mission_tests.py
  api/api/views/viewsets/mission.py
  api/core/settings.py
Labels: back-end

#151 release 0.0.13 :sparkles:
  .github/workflows/api-unit-tests.yml
  api/api/management/middlewares.py
  api/api/migrations/0001_initial.py
  api/api/migrations/0002_alter_vulnerability_images.py
  api/api/migrations/0003_rename_is_disabled_auth_is_enabled_and_more.py
  api/api/migrations/0004_notes_title.py
  api/api/migrations/0005_alter_mission_team_alter_team_leader.py
  api/api/migrations/0006_crtsh.py
  api/api/models/__init__.py
  api/api/models/mission.py
  api/api/serializers/mission.py
  api/api/services/__init__.py
  api/api/services/sendgrid_mail.py
  api/api/tests/helpers.py
  api/api/tests/mission_tests.py
  api/api/views/__init__.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/mission.py
  api/core/settings.py
  api/core/urls.py
  api/requirements.txt
  web/.env.example
  web/package.json
  web/src/App.tsx
  web/src/assets/strings/en/mission_scope.json
  web/src/component/DeleteConfirm.tsx
  web/src/component/SideBar/SideBar.scss
  web/src/component/SideBar/SideBarData.tsx
  web/src/component/SideBar/TopBar.tsx
  web/src/config.ts
  web/src/global-variable.scss
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/EditMission/CreateMission.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/Home/Form/ContactForm.tsx
  web/src/pages/MissionDetail/MissionDetail.scss
  web/src/pages/MissionDetail/MissionDetail.tsx
  web/src/pages/MissionDetail/Scope.tsx
  web/src/pages/SignUp/ConfirmEmail.tsx
  web/src/pages/SignUp/SignUp.scss
  web/src/pages/SignUp/SignUp.tsx
  web/src/pages/Team/CreateTeam.tsx
  web/src/pages/Team/EditTeam.tsx
  web/src/pages/Team/Team.tsx
  web/src/pages/Team/TeamList.tsx
  web/src/pages/Vulnerability/AddVul.tsx
  web/yarn.lock
Labels: release

#148 feat(api): integrate s3Bucket class to upload files
  api/api/models/mission.py
  api/api/serializers/vulns.py
  api/api/services/s3.py
Labels: back-end

#152 fix(api): call to `crt.sh` returns 500
  api/api/models/mission.py
  api/api/services/crtsh.py
  api/api/views/viewsets/mission.py
  api/core/urls.py
Labels: bug

#159 feat(api): adding support for sendgrid templates
  api/.env-dist
  api/api/models/__init__.py
Labels: back-end

#165 feat(web): crtsh integration to dashboard
  api/api/services/crtsh.py
  api/api/views/viewsets/mission.py
  web/package.json
  web/src/assets/strings/en/crt.json
  web/src/component/SideBar/SideBar.tsx
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/SubDashboards/CrtSh.tsx
  web/src/pages/Dashboard/SubDashboards/DorkEngine.tsx
  web/src/pages/MissionDetail/MissionDetail.scss
  web/src/pages/SignUp/SignUp.tsx
Labels: front-end, dependencies, in-pld

#163 fix(api): s3 image upload
  .github/workflows/api-unit-tests.yml
  api/.env-dist
  api/api/migrations/0005_alter_vulnerability_images.py
  api/api/models/vulns.py
  api/api/serializers/vulns.py
  api/api/services/s3.py
  api/api/views/viewsets/mission.py
  api/api/views/viewsets/vulns.py
  api/requirements.txt
  services/nginx/nginx.conf
  web/src/pages/Vulnerability/AddVul.tsx
Labels: bug, back-end

#168 fix(web): landing page update + front end style fix
  web/index.html
  web/src/App.tsx
  web/src/assets/cover.jpg
  web/src/assets/strings/en/crt.json
  web/src/assets/strings/en/privacypo.json
  web/src/assets/strings/en/team.json
  web/src/assets/strings/en/termofuse.json
  web/src/assets/strings/en/timeline.json
  web/src/assets/voron-logo.svg
  web/src/component/Footer/Footer.scss
  web/src/component/Footer/Footer.tsx
  web/src/component/NavBar/NavBar.scss
  web/src/component/NavBar/NavBar.tsx
  web/src/component/SideBar/SideBar.scss
  web/src/component/SideBar/SideBar.tsx
  web/src/global-variable.scss
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/SubDashboards/DorkEngine.tsx
  web/src/pages/EditMission/Mission.scss
  web/src/pages/Home/About/About.scss
  web/src/pages/Home/About/About.tsx
  web/src/pages/Home/Form/ContactForm.module.scss
  web/src/pages/Home/Home.scss
  web/src/pages/Home/PrivacyPolicy.tsx
  web/src/pages/Home/TermOfUse.tsx
  web/src/pages/Home/Text.scss
  web/src/pages/Login/Login.tsx
  web/src/pages/Settings/Settings-pages/set-security.tsx
  web/src/pages/Settings/Settings-pages/set-team.tsx
  web/src/pages/Settings/Settings-pages/team.scss
  web/src/pages/Settings/Settings.scss
  web/src/pages/Settings/Settings.tsx
  web/src/pages/SignUp/SignUp.scss
  web/src/pages/SignUp/SignUp.tsx
Labels: front-end, in-pld

#167 fix(web): user information update
  web/src/component/SideBar/TopBar.tsx
  web/src/pages/Dashboard/SubDashboards/CrtSh.tsx
  web/src/pages/Login/Login.tsx
  web/src/pages/Settings/Settings-pages/setting-account.tsx
Labels: enhancement, front-end, in-pld

#161 feat(api): pdf generation
  .github/workflows/deploy.yml
  api/Dockerfile
  api/api/management/commands/init_first_user.py
  api/api/migrations/0002_alter_mission_scope.py
  api/api/migrations/0006_merge_20230510_1424.py
  api/api/models/mission.py
  api/api/views/report.py
  api/core/urls.py
  api/pdf-templates/NASA-template/coverpage-template.html
  api/pdf-templates/NASA-template/introduction-template.html
  api/pdf-templates/NASA-template/resultsinbrief-template.html
  api/pdf-templates/NASA-template/tableofcontent-template.html
  api/pdf-templates/hackmanit-template/coverpage-template.html
  api/pdf-templates/hackmanit-template/generalconditionsandscope-template.html
  api/pdf-templates/hackmanit-template/hackmanit-logo-1.jpg
  api/pdf-templates/hackmanit-template/hackmanit-logo-2.png
  api/pdf-templates/hackmanit-template/main.css
  api/pdf-templates/hackmanit-template/projectinfo-template.html
  api/pdf-templates/hackmanit-template/recommendation-template.html
  api/pdf-templates/hackmanit-template/references-template.html
  api/pdf-templates/hackmanit-template/summary-template.html
  api/pdf-templates/hackmanit-template/tableofcontent-template.html
  api/pdf-templates/hackmanit-template/toc.xsl
  api/pdf-templates/hackmanit-template/weaknesses-template.html
  api/requirements.txt
  api/scripts/setup.sh
  api/scripts/setup_mac.sh
Labels: back-end

#170 feat(api): image support in pdf generation
  api/api/serializers/vulns.py
  api/api/services/s3.py
  api/api/views/report.py
Labels: back-end

#171 feat(web): Mission API / Scope / Recon integration
  api/Dockerfile
  api/api/models/mission.py
  api/api/permissions.py
  api/api/serializers/vulns.py
  api/api/services/s3.py
  api/api/tests/notes_tests.py
  api/api/views/report.py
  api/api/views/viewsets/vulns.py
  api/core/urls.py
  api/scripts/entrypoint.sh
  services/nginx/nginx.conf
  web/.eslintrc.cjs
  web/src/assets/strings/en/mission_scope.json
  web/src/assets/strings/en/recon.json
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/Dashboard/SubDashboards/Vulnerability.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/MissionDetail/MissionDetail.scss
  web/src/pages/MissionDetail/Scope.tsx
  web/src/pages/SignUp/ConfirmEmail.tsx
  web/src/pages/Vulnerability/AddVul.tsx
  web/yarn.lock
Labels: front-end, back-end

#176 fix(web): enter action on scope input
  web/src/pages/EditMission/CreateMission.tsx
Labels: front-end
