Repository vrn-sh/erp, pull requests merged in 2023-09, with the labels that each got.

#252 feat(api): added caching system to views and viewsets
  api/api/models/__init__.py
  api/api/models/mission.py
  api/api/models/vulns.py
  api/api/permissions.py
  api/api/serializers/mission.py
  api/api/serializers/vulns.py
  api/api/tests/vuln_tests.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/mission.py
  api/api/views/viewsets/vulns.py
  api/core/urls.py
Labels: back-end

#261 feat(web): remove search on file from team creation form
  web/src/component/SideBar/SideBar.scss
  web/src/component/SideBar/TopBar.tsx
  web/src/pages/MissionDetail/Scope.tsx
  web/src/pages/Team/CreateTeam.tsx
  web/src/pages/Team/EditTeam.tsx
Labels: bug, enhancement, front-end

#267 feat(web): profile page improvements
  web/.eslintrc.cjs
  web/src/assets/testpp.png
  web/src/component/SideBar/TopBar.tsx
  web/src/config.ts
  web/src/pages/Dashboard/SubDashboards/CrtSh.tsx
  web/src/pages/Profile/Profile.scss
  web/src/pages/Profile/Profile.tsx
  web/src/pages/Profile/TableRow.tsx
  web/src/pages/Profile/TableSection.tsx
  web/src/pages/Settings/Settings-pages/setting-account.tsx
  web/src/pages/Vulnerability/VulnDetail.tsx
Labels: front-end, dependencies

#274 feat(api): formulaire pdf génération contenu back
  .github/workflows/api-unit-tests.yml
  api/api/management/commands/init_templates.py
  api/api/migrations/0013_reporttemplate_reporthtml.py
  api/api/migrations/0017_merge_20230920_1948.py
  api/api/models/report/__init__.py
  api/api/models/report/academic_paper.py
  api/api/models/report/generate_html.py
  api/api/models/report/report.py
  api/api/tests/__init__.py
  api/api/tests/mission_tests.py
  api/api/tests/report_tests.py
  api/api/views/report.py
  api/api/views/report/__init__.py
  api/api/views/report/report.py
  api/core/urls.py
  api/pdf-templates/NASA-template/main.css
  api/pdf-templates/NASA-template/toc.xsl
  api/pdf-templates/academic-template/coverpage-template.html
  api/pdf-templates/academic-template/main.css
  api/pdf-templates/hackmanit-template/coverpage-template.html
  api/pdf-templates/hackmanit-template/weaknesses-template.html
  api/pdf-templates/red4sec-template/coverpage-template.html
  api/pdf-templates/red4sec-template/generalconditionsandscope-template.html
  api/pdf-templates/red4sec-template/main.css
  api/pdf-templates/red4sec-template/red4sec.png
  api/pdf-templates/red4sec-template/sample.pdf
Labels: back-end

#273 feat(web): amélioration de la side bar
  web/src/component/SideBar/SideBar.tsx
  web/src/component/SideBar/SideBarData.tsx
  web/src/component/SideBar/SideBarMenu.type.ts
  web/src/pages/Login/Login.tsx
  web/src/pages/MissionDetail/MissionDetail.tsx
  web/src/pages/MissionDetail/Scope.tsx
Labels: front-end, in-pld

#276 feat(web): api search engine
  api/api/views/search.py
  web/src/component/SideBar/SideBar.scss
  web/src/component/SideBar/TopBar.tsx
Labels: enhancement, front-end, in-pld

#268 feat(web): make password change feature more accessible
  web/src/pages/Settings/Settings-pages/securityTeam.tsx
  web/src/pages/Settings/Settings-pages/securityUser.tsx
  web/src/pages/Settings/Settings-pages/set-security.tsx
  web/src/pages/Settings/Settings.scss
Labels: enhancement, front-end, in-pld

#279 feat(web): amelioration de la page note
  web/src/pages/Dashboard/SubDashboards/Notes/AddNote.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/Notes.tsx
Labels: enhancement, front-end, in-pld

#285 feat(web): status scope
  web/src/pages/MissionDetail/MissionDetail.tsx
  web/src/pages/MissionDetail/Scope.tsx
Labels: bug, front-end, dependencies

#286 feat(web): pdf-generation form
  api/api/management/commands/init_templates.py
  api/api/models/report/academic_paper.py
  api/api/views/report/report.py
  api/scripts/entrypoint.sh
  api/scripts/setup.sh
  api/scripts/wkhtmltopdf.sh
  web/package.json
  web/public/templates/template_0.png
  web/public/templates/template_1.png
  web/public/templates/template_2.png
  web/public/templates/template_3.png
  web/public/templates/template_4.png
  web/src/component/BackButton.scss
  web/src/component/BackButton.tsx
  web/src/component/SelectMission.tsx
  web/src/component/SideBar/SideBarData.tsx
  web/src/component/Tooltip/Tooltip.scss
  web/src/component/Tooltip/Tooltip.tsx
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/SubDashboard.tsx
  web/src/pages/Dashboard/SubDashboards/CrtSh.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Markdown/Editor.scss
  web/src/pages/Dashboard/SubDashboards/Report/Markdown/Editor.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Markdown/MarkdownHelper.scss
  web/src/pages/Dashboard/SubDashboards/Report/Markdown/MarkdownHelper.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Report.scss
  web/src/pages/Dashboard/SubDashboards/Report/Report.tsx
Labels: front-end, back-end
