Repository vrn-sh/erp, pull requests merged in 2023-11, with the labels that each got.

#365 feat(web): Refacto de la page Accueil
  web/src/component/SideBar/SideBar.tsx
  web/src/pages/Dashboard/Accueil.scss
  web/src/pages/Dashboard/Accueil.tsx
  web/src/pages/Home/About/About.scss
  web/src/pages/Home/Plan/Plan.scss
Labels: bug, landing-page, front-end, dependencies

#367 feat(web): Complete refacto of page accueil
  web/src/assets/strings/en/payload.json
  web/src/component/Tooltip/Tooltip.scss
  web/src/component/Tooltip/Tooltip.tsx
  web/src/pages/Dashboard/Accueil.tsx
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/DashboardMission.type.ts
  web/src/pages/Dashboard/SubDashboard.tsx
  web/src/pages/Dashboard/SubDashboards/CrtSh.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/AddNote.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/Notes.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Markdown/Editor.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Report.tsx
  web/src/pages/Dashboard/SubDashboards/Vulnerability.tsx
  web/src/pages/MissionDetail/MissionDetail.scss
  web/src/pages/MissionDetail/MissionDetail.tsx
  web/src/pages/MissionDetail/Recon.scss
  web/src/pages/MissionDetail/Scope.tsx
Labels: front-end

#369 feat(web): Ajout de la description de mission au front
  web/src/pages/Dashboard/Accueil.tsx
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/SubDashboard.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/EditMission/CreateMission.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/MissionDetail/MissionDetail.scss
  web/src/pages/MissionDetail/MissionDetail.tsx
Labels: enhancement, front-end

#372 feat(api): Fix credentials viewets
  api/api/migrations/0026_alter_credentials_mission.py
  api/api/models/mission.py
  api/api/permissions.py
  api/api/views/viewsets/mission.py
  web/src/pages/MissionDetail/Credential.tsx
Labels: back-end

#361 feat(api): added logo to mission (model, serializer, views)
  api/api/migrations/0024_mission_logo.py
  api/api/migrations/0027_merge_20231116_1548.py
  api/api/models/mission.py
  api/api/serializers/mission.py
  api/api/views/viewsets/mission.py
  web/src/pages/EditMission/CreateMission.tsx
  web/src/pages/MissionDetail/MissionDetail.tsx
Labels: back-end

#374 fix(api): added logo to mission
  api/api/views/viewsets/mission.py
Labels: back-end
