Repository vrn-sh/erp, pull requests merged in 2023-03, with the labels that each got.

#88 feat(web): adding dashboard skeleton
  web/.eslintrc.cjs
  web/package.json
  web/src/App.tsx
  web/src/assets/strings/en/team.json
  web/src/component/NavBar/NavBar.scss
  web/src/component/SideBar/SideBar.scss
  web/src/component/SideBar/SideBar.tsx
  web/src/component/SideBar/SideBarData.tsx
  web/src/component/SideBar/SideBarMenu.type.ts
  web/src/component/SideBar/TopBar.tsx
  web/src/global-variable.scss
  web/src/main.scss
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/Dashboard.tsx
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/DashboardMission.type.ts
  web/src/pages/Dashboard/SubDashboard.tsx
  web/src/pages/Home/About/About.scss
  web/src/pages/Home/About/About.tsx
  web/src/pages/Home/Home.scss
  web/src/pages/Home/Team/Team.scss
  web/src/pages/Home/Team/Team.tsx
  web/src/pages/Login/Login.scss
  web/src/pages/Login/Login.tsx
  web/yarn.lock
Labels: front-end

#89 fix(web): center alignment on login modal
  web/src/main.scss
  web/src/pages/Login/Login.scss
  web/src/pages/Login/Login.tsx
Labels: bug, front-end

#92 fix(api): Note & Vulnerability CRUD
  api/api/management/commands/init_builtin_vuln_types.py
  api/api/migrations/0004_alter_notes_author_alter_vulnerability_author_squashed_0009_alter_vulnerability_vuln_type.py
  api/api/models/__init__.py
  api/api/models/vulns.py
  api/api/permissions.py
  api/api/serializers/__init__.py
  api/api/serializers/utils.py
  api/api/serializers/vulns.py
  api/api/tests/__init__.py
  api/api/tests/notes_tests.py
  api/api/tests/vuln_tests.py
  api/api/views/viewsets/vulns.py
  api/scripts/setup.sh
Labels: bug, back-end

#95 feat(api): Mission model CRUD
  api/api/migrations/0010_mission.py
  api/api/models/__init__.py
  api/api/models/mission.py
  api/api/models/vulns.py
  api/api/serializers/mission.py
  api/api/tests/__init__.py
  api/api/tests/mission_tests.py
  api/api/views/viewsets/mission.py
  api/core/urls.py
Labels: back-end, in-pld

#96 feat(api): Team CRUD + Renaming Admin Field to Manager
  .github/workflows/api-unit-tests.yml
  .gitignore
  api/.coveragerc
  api/api/management/commands/init_builtin_vuln_types.py
  api/api/management/commands/init_first_user.py
  api/api/migrations/0001_initial.py
  api/api/migrations/0002_imagemodel_vulntype_alter_pentester_options_and_more.py
  api/api/migrations/0003_builtin_vuln_types.py
  api/api/migrations/0004_alter_notes_author_alter_vulnerability_author_squashed_0009_alter_vulnerability_vuln_type.py
  api/api/migrations/0010_mission.py
  api/api/models/__init__.py
  api/api/models/mission.py
  api/api/models/vulns.py
  api/api/permissions.py
  api/api/serializers/__init__.py
  api/api/serializers/utils.py
  api/api/tests/__init__.py
  api/api/tests/helpers.py
  api/api/tests/mission_tests.py
  api/api/tests/notes_tests.py
  api/api/tests/vuln_tests.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/mission.py
  api/api/views/viewsets/vulns.py
  api/core/urls.py
Labels: back-end

#94 feat(web): API Authentication Integration (Login & Register)
  api/core/settings.py
  api/requirements.txt
  web/.env.example
  web/.eslintrc.cjs
  web/package.json
  web/src/component/SideBar/SideBar.scss
  web/src/component/SideBar/SideBar.tsx
  web/src/config.ts
  web/src/global-variable.scss
  web/src/main.scss
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Home/About/About.scss
  web/src/pages/Home/Home.scss
  web/src/pages/Home/Team/Team.scss
  web/src/pages/Login/Login.scss
  web/src/pages/Login/Login.tsx
  web/src/pages/SignUp/SignUp.tsx
  web/yarn.lock
Labels: front-end

#97 Release 006 :sparkles:
  .github/workflows/api-unit-tests.yml
  .gitignore
  api/.coveragerc
  api/api/management/commands/init_builtin_vuln_types.py
  api/api/management/commands/init_first_user.py
  api/api/migrations/0001_initial.py
  api/api/migrations/0002_imagemodel_vulntype_alter_pentester_options_and_more.py
  api/api/migrations/0003_builtin_vuln_types.py
  api/api/models/__init__.py
  api/api/models/mission.py
  api/api/models/vulns.py
  api/api/permissions.py
  api/api/serializers/__init__.py
  api/api/serializers/mission.py
  api/api/serializers/utils.py
  api/api/serializers/vulns.py
  api/api/tests/__init__.py
  api/api/tests/helpers.py
  api/api/tests/mission_tests.py
  api/api/tests/notes_tests.py
  api/api/tests/vuln_tests.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/mission.py
  api/api/views/viewsets/vulns.py
  api/core/settings.py
  api/core/urls.py
  api/requirements.txt
  api/scripts/setup.sh
  web/.env.example
  web/.eslintrc.cjs
  web/package.json
  web/src/component/SideBar/SideBar.scss
  web/src/component/SideBar/SideBar.tsx
  web/src/config.ts
  web/src/global-variable.scss
  web/src/main.scss
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Home/About/About.scss
  web/src/pages/Home/Home.scss
  web/src/pages/Home/Team/Team.scss
  web/src/pages/Login/Login.scss
  web/src/pages/Login/Login.tsx
  web/src/pages/SignUp/SignUp.tsx
  web/yarn.lock
Labels: release

#98 feat(web): adding timeline to landing page
  .github/workflows/api-unit-tests.yml
  .github/workflows/frontend-unit-tests.yml
  web/package.json
  web/src/assets/strings/en/team.json
  web/src/assets/strings/en/timeline.json
  web/src/component/NavBar/NavBar.tsx
  web/src/pages/Home/Home.tsx
  web/src/pages/Home/Timeline/Timeline.scss
  web/src/pages/Home/Timeline/Timeline.tsx
  web/yarn.lock
Labels: front-end

#99 feat(api|web): improving default vuln types
  api/api/management/commands/init_builtin_vuln_types.py
  api/api/models/vulns.py
  api/api/serializers/vulns.py
  api/api/tests/vuln_tests.py
  web/src/assets/strings/en/vulnerabilities.json
Labels: front-end, back-end

#100 feat(api): Recon CRUD + team permission middleware
  api/.coveragerc
  api/api/backends.py
  api/api/migrations/0001_initial.py
  api/api/models/__init__.py
  api/api/models/mission.py
  api/api/models/vulns.py
  api/api/permissions.py
  api/api/serializers/__init__.py
  api/api/serializers/mission.py
  api/api/serializers/utils.py
  api/api/serializers/vulns.py
  api/api/tests/__init__.py
  api/api/tests/helpers.py
  api/api/tests/mission_tests.py
  api/api/tests/notes_tests.py
  api/api/tests/vuln_tests.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/mission.py
  api/api/views/viewsets/vulns.py
  api/core/urls.py
Labels: back-end

#101 Release 007 :sparkles:
  .github/workflows/api-unit-tests.yml
  .github/workflows/frontend-unit-tests.yml
  api/.coveragerc
  api/api/backends.py
  api/api/management/commands/init_builtin_vuln_types.py
  api/api/migrations/0001_initial.py
  api/api/models/__init__.py
  api/api/models/mission.py
  api/api/models/vulns.py
  api/api/permissions.py
  api/api/serializers/__init__.py
  api/api/serializers/mission.py
  api/api/serializers/utils.py
  api/api/serializers/vulns.py
  api/api/tests/__init__.py
  api/api/tests/helpers.py
  api/api/tests/mission_tests.py
  api/api/tests/notes_tests.py
  api/api/tests/vuln_tests.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/mission.py
  api/api/views/viewsets/vulns.py
  api/core/urls.py
  web/package.json
  web/src/assets/strings/en/team.json
  web/src/assets/strings/en/timeline.json
  web/src/assets/strings/en/vulnerabilities.json
  web/src/component/NavBar/NavBar.tsx
  web/src/pages/Home/Home.tsx
  web/src/pages/Home/Timeline/Timeline.scss
  web/src/pages/Home/Timeline/Timeline.tsx
  web/yarn.lock
Labels: release

#102 fix(web): adding `id` field to `vulnerabilities.json`
  web/src/assets/strings/en/vulnerabilities.json
Labels: front-end

#103 75 3jh add dork engine page to missions menu
  web/src/assets/strings/en/dorks.json
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/SubDashboard.tsx
  web/src/pages/Dashboard/SubDashboards/DorkEngine.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
Labels: enhancement, front-end

#104 feat(web): readme docs
  web/README.md
Labels: documentation, enhancement, front-end
