Repository vrn-sh/erp, pull requests merged in 2023-10, with the labels that each got.

#349 fix(web): adding 'Enter' keyword to some buttons
  web/src/pages/Dashboard/SubDashboards/CrtSh.tsx
  web/src/pages/Dashboard/SubDashboards/DorkEngine.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/AddNote.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/ViewNote.tsx
  web/src/pages/EditMission/CreateMission.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/Login/Login.tsx
  web/src/pages/MissionDetail/HunterIo/HunterDomain.tsx
  web/src/pages/MissionDetail/HunterIo/HunterEmailF.tsx
  web/src/pages/MissionDetail/HunterIo/HunterEmailV.tsx
  web/src/pages/Settings/Settings-pages/securityTeam.tsx
  web/src/pages/Settings/Settings-pages/securityUser.tsx
  web/src/pages/Settings/Settings-pages/setting-account.tsx
  web/src/pages/SignUp/SignUp.tsx
  web/src/pages/Team/CreateTeam.tsx
  web/src/pages/Team/EditTeam.tsx
  web/src/pages/Team/ViewTeam.tsx
  web/src/pages/Vulnerability/AddVul.tsx
  web/src/pages/Vulnerability/EditVuln.tsx
Labels: front-end, dependencies

#350 feat(api): added first and last name to auth model
  api/api/migrations/0021_alter_auth_first_name_alter_auth_last_name.py
  api/api/models/__init__.py
  api/api/views/viewsets/__init__.py
Labels: back-end

#351 feat(web): pdf-generation form
  api/api/management/commands/init_templates.py
  api/api/migrations/0018_alter_mission_options_reporthtml_html_file_and_more.py
  api/api/migrations/0021_merge_20231011_1454.py
  api/api/models/report/academic_paper.py
  api/api/models/report/report.py
  api/api/serializers/report.py
  api/api/tests/__init__.py
  api/api/tests/report_tests.py
  api/api/views/report/report.py
  api/core/urls.py
  web/src/component/Input.tsx
  web/src/component/Tooltip/Tooltip.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Report.tsx
Labels: front-end, back-end, in-pld

#362 feat(web): add new api wappalyzer to front
  web/src/assets/strings/en/team.json
  web/src/pages/Home/About/About.scss
  web/src/pages/Home/Form/ContactForm.module.scss
  web/src/pages/Home/Plan/Plan.scss
  web/src/pages/Home/Plan/Plan.tsx
  web/src/pages/MissionDetail/Recon.scss
  web/src/pages/MissionDetail/Recon.tsx
Labels: landing-page, front-end, dependencies

#364 feat(web): implementing new dashboard page
  web/src/App.tsx
  web/src/component/SideBar/SideBar.scss
  web/src/component/SideBar/SideBar.tsx
  web/src/component/SideBar/SideBarData.tsx
  web/src/pages/Dashboard/Accueil.scss
  web/src/pages/Dashboard/Accueil.tsx
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/Dashboard.tsx
  web/src/pages/Dashboard/DashboardMission.tsx
  web/src/pages/Dashboard/SubDashboard.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Markdown/Editor.scss
  web/src/pages/Home/Plan/Plan.tsx
  web/src/pages/Login/Login.tsx
  web/src/pages/MissionDetail/Recon.scss
  web/src/pages/MissionDetail/Recon.tsx
  web/src/pages/Team/TeamList.tsx
Labels: front-end, dependencies
