Repository vrn-sh/erp, pull requests merged in 2023-02, with the labels that each got.

#1 feat(api): refactoring & improving tests
  .github/ISSUE_TEMPLATE/issue.md
  api/.gitignore
  api/.pylintrc
  api/.tool-versions
  api/README.md
  api/api/apps.py
  api/api/backends.py
  api/api/management/commands/init_first_user.py
  api/api/migrations/0001_initial.py
  api/api/models/__init__.py
  api/api/permissions.py
  api/api/serializers/__init__.py
  api/api/serializers/utils.py
  api/api/tests/__init__.py
  api/api/tests/helpers.py
  api/api/views/__init__.py
  api/api/views/viewsets/__init__.py
  api/core/settings.py
  api/core/urls.py
  api/manage.py
  api/requirements.txt
  api/scripts/setup.sh
Labels: documentation, enhancement

#20 feat(services): docker-compose+nginx setup
  .github/workflows/compose.yml
  .gitignore
  api/.env-dist
  api/README.md
  docker-compose.yml
  services/nginx/env.conf.template
  services/nginx/nginx.conf
Labels: ci / deployment

#29 feat(docs): main README with install instructions
  README.md
  api/README.md
  toolbox/docker-compose.dev.yml
Labels: documentation

#37 feat(ci): deploy action on push
  .github/workflows/compose.yml
  .github/workflows/deploy.yml
  api/.env-dist
  api/api/permissions.py
  api/scripts/entrypoint.sh
  docker-compose.yml
  services/nginx/env.conf.template
  services/nginx/nginx.conf
Labels: enhancement, ci / deployment

#38 feat(web): improving landing page with ✨corporate bullshit ✨
  web/src/assets/strings/en/about.json
  web/src/pages/Home/About/About.scss
  web/src/pages/Home/About/About.tsx
  web/src/pages/Home/Home.scss
  web/src/pages/Home/Home.tsx
Labels: enhancement, front-end

#55 feat(web): login UI page
  web/package.json
  web/src/App.tsx
  web/src/component/Footer/Footer.tsx
  web/src/global-variable.scss
  web/src/pages/LogIn.tsx
  web/src/pages/Login/Login.scss
  web/src/pages/Login/Login.tsx
Labels: front-end

#54 feat(meta): adding bug report & pull request templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/pull_request_template.md
Labels: enhancement, meta

#56 Release 002
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/pull_request_template.md
  .github/workflows/api-unit-tests.yml
  .github/workflows/deploy.yml
  api/api/migrations/0001_initial.py
  api/api/tests/__init__.py
  api/api/tests/helpers.py
  api/core/settings.py
  web/package.json
  web/src/App.tsx
  web/src/component/Footer/Footer.tsx
  web/src/global-variable.scss
  web/src/pages/LogIn.tsx
  web/src/pages/Login/Login.scss
  web/src/pages/Login/Login.tsx
Labels: release

#58 feat(ci): front-end linting ci
  .github/workflows/frontend-lint.yml
  .github/workflows/frontend-unit-tests.yml
  .gitignore
  .tool-versions
  web/.eslintrc.cjs
  web/.prettierrc.cjs
  web/README.md
  web/package.json
  web/src/App.tsx
  web/src/__test__/Home.spec.tsx
  web/src/__test__/setup.ts
  web/src/component/Footer/Footer.tsx
  web/src/component/NavBar/NavBar.tsx
  web/src/main.tsx
  web/src/pages/Home/About/About.tsx
  web/src/pages/Home/Home.tsx
  web/src/pages/Home/Team/Team.tsx
  web/src/pages/Login/Login.scss
  web/src/pages/Login/Login.tsx
  web/src/pages/SignUp.tsx
  web/tsconfig.json
  web/tsconfig.node.json
  web/vite.config.ts
  web/vitest.config.js
  web/yarn.lock
Labels: enhancement, front-end, ci / deployment, dependencies

#43 feat(web): carousel to introduce the team ✨
  web/.eslintrc.cjs
  web/package.json
  web/public/avatarph.png
  web/src/assets/strings/en/team.json
  web/src/component/Footer/Footer.scss
  web/src/component/NavBar/NavBar.tsx
  web/src/pages/Home/Team/Team.scss
  web/src/pages/Home/Team/Team.tsx
  web/src/pages/Login/Login.scss
  web/yarn.lock
Labels: enhancement, front-end

#60 feat(docs): improving docs for local install
  .github/workflows/compose.yml
  README.md
  api/.env-dist
  api/README.md
  api/scripts/setup.sh
  toolbox/docs/CONTRIBUTE.md
  web/README.md
Labels: documentation, enhancement

#61 chore(build): bumping docker dependencies
  README.md
  api/README.md
  docker-compose.yml
  web/Dockerfile
Labels: documentation, ci / deployment, dependencies

#63 feat(meta): improve security conformity with secure headers, etc
  .github/workflows/api-unit-tests.yml
  api/.env-dist
  api/Dockerfile
  api/README.md
  api/api/management/middlewares.py
  api/api/views/__init__.py
  api/core/settings.py
  api/core/urls.py
  api/gunicorn.conf.py
  api/requirements.txt
  docker-compose.yml
  services/nginx/nginx.conf
  toolbox/docs/CONTRIBUTE.md
  toolbox/docs/DEPLOY.md
  web/Dockerfile
Labels: documentation, enhancement, ci / deployment

#64 Release 003 ✨
  .github/workflows/api-unit-tests.yml
  .github/workflows/compose.yml
  .github/workflows/frontend-lint.yml
  .github/workflows/frontend-unit-tests.yml
  .gitignore
  .tool-versions
  README.md
  api/.env-dist
  api/Dockerfile
  api/README.md
  api/api/management/middlewares.py
  api/api/views/__init__.py
  api/core/settings.py
  api/core/urls.py
  api/gunicorn.conf.py
  api/requirements.txt
  api/scripts/setup.sh
  docker-compose.yml
  services/nginx/nginx.conf
  toolbox/docs/CONTRIBUTE.md
  toolbox/docs/DEPLOY.md
  web/.eslintrc.cjs
  web/.prettierrc.cjs
  web/Dockerfile
  web/README.md
  web/package.json
  web/public/avatarph.png
  web/src/App.tsx
  web/src/__test__/Home.spec.tsx
  web/src/__test__/setup.ts
  web/src/assets/strings/en/team.json
  web/src/component/Footer/Footer.scss
  web/src/component/Footer/Footer.tsx
  web/src/component/NavBar/NavBar.tsx
  web/src/main.tsx
  web/src/pages/Home/About/About.tsx
  web/src/pages/Home/Home.tsx
  web/src/pages/Home/Team/Team.scss
  web/src/pages/Home/Team/Team.tsx
  web/src/pages/Login/Login.scss
  web/src/pages/Login/Login.tsx
  web/src/pages/SignUp.tsx
  web/tsconfig.json
  web/tsconfig.node.json
  web/vite.config.ts
  web/vitest.config.js
  web/yarn.lock
Labels: release

#70 fix(api): Access to Redoc documentation on development
  api/.env-dist
  api/README.md
  api/core/settings.py
  api/core/urls.py
  api/scripts/nuke.sh
  api/scripts/setup.sh
Labels: back-end

#82 feat(api): Note CRUD
  api/.tool-versions
  api/api/management/commands/init_first_user.py
  api/api/management/middlewares.py
  api/api/migrations/0001_initial.py
  api/api/models/__init__.py
  api/api/models/vulns.py
  api/api/permissions.py
  api/api/serializers/__init__.py
  api/api/serializers/vulns.py
  api/api/tests/__init__.py
  api/api/tests/helpers.py
  api/api/tests/notes_tests.py
  api/api/views/viewsets/__init__.py
  api/api/views/viewsets/vulns.py
  api/core/settings.py
  api/core/urls.py
  api/scripts/setup.sh
Labels: back-end

#85 fix(api): runtime crashes when loading swagger
  api/api/serializers/vulns.py
Labels: bug, back-end
