Repository vrn-sh/erp, pull requests merged in 2024-01, with the labels that each got.

#395 Amélioration détaillées du site avant Delivery
  web/.eslintrc.cjs
  web/package.json
  web/src/App.tsx
  web/src/assets/about-action.svg
  web/src/assets/strings/en/about.json
  web/src/component/Footer/Footer.tsx
  web/src/pages/Dashboard/Accueil.scss
  web/src/pages/Dashboard/Accueil.tsx
  web/src/pages/Dashboard/Dashboard.scss
  web/src/pages/Dashboard/SubDashboards/Vulnerability.tsx
  web/src/pages/Dashboard/shellcode/BasicShellcode.tsx
  web/src/pages/Dashboard/shellcode/MyPhShellcode.tsx
  web/src/pages/EditMission/CreateMission.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/Home/About/About.scss
  web/src/pages/Home/About/About.tsx
  web/src/pages/Home/Home.tsx
  web/src/pages/Login/Login.tsx
  web/src/pages/MissionDetail/Credential.tsx
  web/src/pages/MissionDetail/MissionDetail.scss
  web/src/pages/MissionDetail/MissionDetail.tsx
  web/src/pages/MissionDetail/Recon.scss
  web/src/pages/MissionDetail/Recon.tsx
  web/src/pages/Profile/Profile.scss
  web/src/pages/Profile/Profile.tsx
  web/src/pages/Profile/TableSection.tsx
  web/src/pages/SignUp/SignUp.tsx
  web/src/pages/Team/CreateTeam.tsx
  web/src/pages/Team/TeamList.tsx
  web/src/pages/Team/ViewTeam.tsx
  web/src/pages/Vulnerability/AddVul.tsx
Labels: bug, front-end

#396 feat(web): Payload form gif documentation
  web/src/assets/BasicShellcode.gif
  web/src/pages/Dashboard/Accueil.tsx
  web/src/pages/Dashboard/shellcode/Documentation.tsx
  web/src/pages/Dashboard/shellcode/MyPhShellcode.tsx
  web/src/pages/Dashboard/shellcode/PayLoadForm.tsx
Labels: enhancement, front-end

#393 feat(api): Finalize mfa support
  api/api/views/mfa.py
  web/src/pages/Settings/Settings-pages/securityUser.tsx
Labels: back-end

#398 feat(web) client info
  web/src/component/DeleteConfirm.tsx
  web/src/main.scss
  web/src/pages/EditMission/Mission.scss
  web/src/pages/MissionDetail/ClientInfo.tsx
  web/src/pages/MissionDetail/CreateClientInfo.tsx
  web/src/pages/MissionDetail/EditClientInfo.tsx
  web/src/pages/MissionDetail/MissionDetail.scss
  web/src/pages/MissionDetail/MissionDetail.tsx
  web/src/pages/Settings/Settings-pages/securityUser.tsx
Labels: front-end, in-pld

#401 feat(web): client list
  web/src/App.tsx
  web/src/component/SideBar/SideBarData.tsx
  web/src/pages/Client/ClientList.tsx
Labels: enhancement, front-end, in-pld

#399 feat(web) gestion loader
  web/src/pages/Dashboard/Accueil.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/Notes.tsx
  web/src/pages/Dashboard/SubDashboards/Vulnerability.tsx
  web/src/pages/MissionDetail/Credential.tsx
  web/src/pages/MissionDetail/Scope.tsx
  web/src/pages/Team/TeamList.tsx
  web/src/pages/Team/ViewTeam.tsx
  web/src/pages/Vulnerability/VulnDetail.tsx
Labels: front-end, in-pld

#402 fix(web): updating packages
  web/package.json
  web/src/pages/Dashboard/SubDashboards/Vulnerability.tsx
Labels: front-end

#404 feat(api): pdf-generation form integration
  api/api/models/report/report.py
  api/api/serializers/report.py
  api/api/tests/__init__.py
  api/api/tests/report_tests.py
  api/api/views/report/report.py
  api/requirements.txt
  web/pnpm-lock.yaml
  web/src/pages/Dashboard/SubDashboards/Report/PDFEditor/PDFEditor.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Report.tsx
  web/yarn.lock
Labels: front-end, back-end

#406 230 3jh formulaire de génération de pdf dans le front
  api/requirements.txt
  web/src/pages/Dashboard/SubDashboards/Report/PDFEditor/PDFEditor.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Report.tsx
Labels: front-end

#407 feat(web): adding the unsubscribe page
  web/src/App.tsx
  web/src/pages/Dashboard/SubDashboards/Report/PDFEditor/PDFEditor.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Report.tsx
  web/src/pages/Home/Unsubscribe/Unsubscribe.scss
  web/src/pages/Home/Unsubscribe/Unsubscribe.tsx
Labels: front-end

#400 fix(web):id vuln & cookie encryption
  web/src/assets/strings/en/vulnerabilities.json
  web/src/component/DeleteConfirm.tsx
  web/src/component/SelectMission.tsx
  web/src/component/SideBar/SideBar.tsx
  web/src/component/SideBar/SideBarData.tsx
  web/src/component/SideBar/TopBar.tsx
  web/src/crypto-utils.ts
  web/src/pages/Client/ClientList.tsx
  web/src/pages/Dashboard/Accueil.tsx
  web/src/pages/Dashboard/SubDashboards/CrtSh.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/AddNote.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/Notes.tsx
  web/src/pages/Dashboard/SubDashboards/Notes/ViewNote.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Markdown/Editor.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Report.tsx
  web/src/pages/Dashboard/SubDashboards/Vulnerability.tsx
  web/src/pages/Dashboard/shellcode/MyPhShellcode.tsx
  web/src/pages/Dashboard/shellcode/PayLoadForm.tsx
  web/src/pages/EditMission/CreateMission.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/Login/Login.tsx
  web/src/pages/Login/MfaLogin.tsx
  web/src/pages/MissionDetail/AddNMAP.tsx
  web/src/pages/MissionDetail/ClientInfo.tsx
  web/src/pages/MissionDetail/CreateClientInfo.tsx
  web/src/pages/MissionDetail/Credential.tsx
  web/src/pages/MissionDetail/EditClientInfo.tsx
  web/src/pages/MissionDetail/HunterIo/HunterDomain.tsx
  web/src/pages/MissionDetail/HunterIo/HunterEmailF.tsx
  web/src/pages/MissionDetail/HunterIo/HunterEmailV.tsx
  web/src/pages/MissionDetail/MissionDetail.tsx
  web/src/pages/MissionDetail/Recon.tsx
  web/src/pages/MissionDetail/Scope.tsx
  web/src/pages/Profile/Profile.tsx
  web/src/pages/Settings/Settings-pages/securityTeam.tsx
  web/src/pages/Settings/Settings-pages/securityUser.tsx
  web/src/pages/Settings/Settings-pages/set-billing.tsx
  web/src/pages/Settings/Settings-pages/set-security.tsx
  web/src/pages/Settings/Settings-pages/set-team.tsx
  web/src/pages/Settings/Settings-pages/setting-account.tsx
  web/src/pages/SignUp/InfoForm.tsx
  web/src/pages/Team/CreateTeam.tsx
  web/src/pages/Team/EditTeam.tsx
  web/src/pages/Team/TeamList.tsx
  web/src/pages/Team/ViewTeam.tsx
  web/src/pages/TokenVerification/TokenVerification.tsx
  web/src/pages/Vulnerability/AddVul.tsx
  web/src/pages/Vulnerability/EditVuln.tsx
  web/src/pages/Vulnerability/VulnDetail.tsx
Labels: enhancement, front-end

#410 fix(web): bunch of random things
  api/api/models/report/report.py
  api/api/serializers/mission.py
  api/api/serializers/report.py
  api/api/tests/report_tests.py
  api/api/views/report/report.py
  web/Dockerfile
  web/package.json
  web/src/pages/Dashboard/SubDashboards/Report/Markdown/Editor.tsx
  web/src/pages/Dashboard/SubDashboards/Report/PDFEditor/PDFEditor.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Report.tsx
  web/src/pages/Dashboard/SubDashboards/Report/types.ts
  web/src/pages/MissionDetail/MissionDetail.tsx
Labels: back-end

#412 fix(web): fix some things like api call or role
  web/src/pages/Client/ClientList.tsx
  web/src/pages/Dashboard/Accueil.tsx
  web/src/pages/Dashboard/SubDashboards/Mission.tsx
  web/src/pages/EditMission/EditMission.tsx
  web/src/pages/MissionDetail/CreateClientInfo.tsx
  web/src/pages/MissionDetail/Credential.tsx
  web/src/pages/MissionDetail/EditClientInfo.tsx
  web/src/pages/MissionDetail/MissionDetail.tsx
  web/src/pages/SignUp/InfoForm.tsx
Labels: front-end

#413 Fix(web) : Fix login
  web/src/pages/Dashboard/SubDashboards/Report/PDFEditor/PDFEditor.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Report.tsx
  web/src/pages/Dashboard/SubDashboards/Report/types.ts
  web/src/pages/Login/Login.tsx
  web/src/pages/MissionDetail/MissionDetail.tsx
Labels: front-end

#414 fixes(web): fixed things lol
  api/api/serializers/report.py
  api/api/views/report/report.py
  api/pdf-templates/academic-template/main.css
  web/src/pages/Dashboard/SubDashboards/Report/PDFEditor/PDFEditor.tsx
  web/src/pages/Dashboard/SubDashboards/Report/Report.tsx
  web/src/pages/Dashboard/SubDashboards/Report/types.ts
Labels: front-end, back-end
